#!/usr/bin/env node
/*
 * run.js — the same benchmark, against the actual published libraries.
 *
 * Shares the corpus, payloads and corruption models with r_and_d/benchmark.js so the
 * rows are directly comparable. What it adds is that these are the real
 * implementations rather than reference models of their techniques — see README.md
 * for why both exist.
 *
 * Thorough by design and slow by consequence. Run periodically, not in CI.
 *
 *   node run.js                       print the tables
 *   node run.js --md FILE             also write markdown
 *   node run.js --js FILE             emit structured results for pages/
 *   VSRMARK_BIN=... node run.js       enable an adapter that needs a local build
 *
 * A library that is not installed is a SKIPPED row, never a zero. Reporting an
 * absent library as 0% robustness would be a lie about software that was never run.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { SAMPLES } = require('../r_and_d/samples.js');
const { PROFILES } = require('../r_and_d/payloads.js');
const { MODELS, makeRng } = require('../r_and_d/corruptions.js');
const { describe, completeness } = require('../r_and_d/attacks.js');

const ARGV = process.argv.slice(2);
const MD_AT = ARGV.indexOf('--md');
const MD_PATH = MD_AT >= 0 ? ARGV[MD_AT + 1] : null;
const JS_AT = ARGV.indexOf('--js');
const JS_PATH = JS_AT >= 0 ? ARGV[JS_AT + 1] : null;

// Structured results, so a rendered page shows measurements rather than a hand-typed
// copy of them. Emitted as a .js file that assigns a global rather than JSON fetched
// at runtime: the pages/ site must work from file:// and from GitHub Pages alike, and
// a fetch would fail on the former.
const DATA = { generated: null, spabVersion: null, libraries: [], models: [], safety: [], capacity: [] };

const ADAPTERS = fs.readdirSync(path.join(__dirname, 'adapters'))
  .filter(f => f.endsWith('.js') && !f.startsWith('_'))
  .map(f => require(path.join(__dirname, 'adapters', f)));

const out = [];
function say(s) { console.log(s); out.push(s); }
function table(headers, rows, aligns) {
  if (!rows.length) { say('_(no libraries available)_\n'); return; }
  const w = headers.map((h, i) => Math.max(h.length, ...rows.map(r => String(r[i]).length)));
  const pad = (s, i) => (aligns && aligns[i] === 'r') ? String(s).padStart(w[i]) : String(s).padEnd(w[i]);
  say('| ' + headers.map(pad).join(' | ') + ' |');
  say('|' + w.map((n, i) => (aligns && aligns[i] === 'r' ? '-'.repeat(n + 1) + ':' : '-'.repeat(n + 2))).join('|') + '|');
  rows.forEach(r => say('| ' + r.map(pad).join(' | ') + ' |'));
  say('');
}
const pct = (a, b) => b ? Math.round(100 * a / b) + '%' : '-';

const samples = SAMPLES;
const payloads = PROFILES;
const SCALES = [1, 4, 12];

// The version, pulled out of the adapter's source string, so it rides in the column
// header rather than only in a table the reader may have scrolled past.
function versionOf(a) {
  const m = /@([\d.]+)/.exec(a.source || '');
  return m ? m[1] : (a.source === 'not installed' ? '' : (/local:([\d.]+)/.exec(a.source || '') || [, ''])[1]);
}
function tryCall(fn) { try { const v = fn(); return (v === undefined) ? null : v; } catch (e) { return null; } }

say('# spab vs other text-watermarking libraries');
say('');
say('Generated by `comparisons/run.js`. Same corpus,');
say('payloads and corruption models as `r_and_d/benchmark.js`.');
say('');

// ---- test conditions, stated before any number ----
//
// A comparison table without its conditions is unusable: the reader cannot tell
// whether a low number means a weak library or a hard test, and cannot reproduce it.
say('## Test conditions');
say('');
{
  const spab = require('../src/js/spab.js');
  table(['condition', 'value'], [
    ['generated', new Date().toISOString().slice(0, 10)],
    ['spab version', spab.VERSION + ' (wire format v' + spab.algorithm.frame.version + ')'],
    ['node', process.version],
    ['platform', process.platform + '/' + process.arch],
    ['text samples', samples.length + ' fixed samples from r_and_d/samples.js'],
    ['cover lengths', SCALES.map(x => x + 'x').join(', ') + ' (each sample repeated)'],
    ['payload sizes', payloads.map(p => p.bytes + 'B').join(', ')],
    ['channel models', Object.keys(MODELS).length + ' (catalogued in r_and_d/attacks.js)'],
    ['intensity', 'median of each model\'s declared range, except the safety table which uses the worst'],
    ['rng seed', 'fixed per cell — the same damage is applied to every library'],
    ['clean round trip', 'required before any damage is applied; a library that cannot carry a payload is excluded from that cell rather than scored 0']
  ]);
}

// ---- availability, stated before any number ----
const live = [];
say('## Libraries');
say('');
{
  const rows = ADAPTERS.map(a => {
    const ok = tryCall(() => a.available()) === true;
    if (ok) live.push(a);
    return [a.name, a.source, ok ? 'yes' : 'SKIPPED', ok ? '' : a.install];
  });
  table(['library', 'source', 'ran', 'to enable'], rows);
  const skipped = ADAPTERS.length - live.length;
  if (skipped) {
    say('_' + skipped + ' of ' + ADAPTERS.length + ' skipped. A skipped library is absent,');
    say('not bad: it produced no numbers and has no rows below._');
    say('');
  }
  const limited = live.filter(a => a.limits);
  if (limited.length) {
    say('Caveats that make a comparison unequal, stated up front:');
    say('');
    limited.forEach(a => say('- **' + a.name + '** — ' + a.limits));
    say('');
  }
}

// ---- 1. can it carry the payload at all ----
say('## 1. Payload capacity');
say('');
say('Whether each library round-trips each payload on a clean cover, before any');
say('damage. `-` means it declined or could not carry it.');
say('');
{
  const rows = live.map(a => {
    const cells = payloads.map(p => {
      let ok = 0, tot = 0;
      for (const s of samples) for (const scale of SCALES) {
        const cover = scale === 1 ? s.text : s.text.repeat(scale);
        tot++;
        const marked = tryCall(() => a.encode(cover, p.text));
        if (marked && tryCall(() => a.decode(marked)) === p.text) ok++;
      }
      return tot ? pct(ok, tot) : '-';
    });
    return [a.name].concat(cells);
  });
  table(['library'].concat(payloads.map(p => p.name + ' (' + p.bytes + 'B)')), rows,
    [null].concat(payloads.map(() => 'r')));
}

// ---- 2. robustness on the shared channel ----
say('## 2. Recovery per corruption model');
say('');
say('Median intensity of each model, over every clean round trip. This is the');
say('comparison the whole folder exists for.');
say('');
const modelNames = Object.keys(MODELS);
{
  const rows = [];
  for (const m of modelNames) {
    const spec = MODELS[m];
    const intensity = spec.intensities[Math.floor(spec.intensities.length / 2)];
    const raw = live.map(a => {
      let ok = 0, tot = 0;
      for (const s of samples) for (const scale of SCALES) for (const p of payloads) {
        const cover = scale === 1 ? s.text : s.text.repeat(scale);
        const marked = tryCall(() => a.encode(cover, p.text));
        if (!marked || tryCall(() => a.decode(marked)) !== p.text) continue;
        tot++;
        if (tryCall(() => a.decode(spec.fn(marked, intensity, makeRng(0xBEEF)))) === p.text) ok++;
      }
      return { lib: a.name, ok: ok, tot: tot, pct: tot ? Math.round(100 * ok / tot) : null };
    });
    DATA.models.push({ model: m, intensity: intensity, note: spec.note, results: raw });
    rows.push([m, String(intensity)].concat(raw.map(r => r.pct === null ? '-' : r.pct + '%')));
  }
  const score = r => r.slice(2).map(v => v === '-' ? -1 : parseInt(v)).reduce((a, b) => a + b, 0);
  rows.sort((a, b) => score(b) - score(a) || a[0].localeCompare(b[0]));
  table(['model', 'intensity'].concat(live.map(a => a.name + ' ' + versionOf(a))), rows,
    [null, 'r'].concat(live.map(() => 'r')));
}

// ---- 3. the safety property, which is not a robustness number ----
say('## 3. Safety: does a damaged mark ever decode to the WRONG payload?');
say('');
say('Distinct from robustness and arguably more important. Losing a watermark is a');
say('non-answer; returning a different one is a false provenance claim. A library');
say('with no integrity check can do the second.');
say('');
{
  const examples = [];
  const rows = live.map(a => {
    let wrong = 0, lost = 0, rec = 0, fp = 0, fpTot = 0, sample = null;
    for (const s of samples) for (const scale of SCALES) {
      const cover = scale === 1 ? s.text : s.text.repeat(scale);
      fpTot++;
      if (tryCall(() => a.decode(cover)) !== null) fp++;         // unmarked text
      for (const p of payloads) {
        const marked = tryCall(() => a.encode(cover, p.text));
        if (!marked || tryCall(() => a.decode(marked)) !== p.text) continue;
        for (const m of modelNames) {
          const spec = MODELS[m];
          const got = tryCall(() => a.decode(spec.fn(marked, spec.intensities[spec.intensities.length - 1], makeRng(11))));
          if (got === p.text) rec++;
          else if (got === null) lost++;
          else { wrong++; if (!sample) sample = { model: m, wrote: p.text, got: String(got) }; }
        }
      }
    }
    if (sample) examples.push({ name: a.name, s: sample });
    DATA.safety.push({ lib: a.name, falsePositive: fp, falsePositiveOf: fpTot,
      wrong: wrong, lost: lost, recovered: rec,
      example: sample ? { model: sample.model, wrote: sample.wrote, got: sample.got.slice(0, 40) } : null });
    return [a.name, fp + '/' + fpTot, wrong, lost, rec,
      wrong === 0 ? 'clean' : '**' + pct(wrong, wrong + lost + rec) + ' wrong**'];
  });
  table(['library', 'false positive', 'wrong payload', 'lost', 'recovered', 'verdict'],
    rows, [null, 'r', 'r', 'r', 'r', null]);
  say('`false positive` is how often unmarked text yielded a payload. `wrong payload`');
  say('is how often a DAMAGED mark decoded to something other than what was written.');
  say('');
  if (examples.length) {
    // What "wrong" actually looks like matters. These are garbage strings, not
    // forged plausible payloads — no library here can be made to emit an attacker's
    // chosen watermark. It is still a failure of the property, because a caller
    // testing `if (decoded)` cannot tell the difference and will attribute wrongly.
    say('What a wrong return looks like — garbage, not a forged watermark, though a');
    say('caller checking `if (decoded)` cannot tell the difference:');
    say('');
    table(['library', 'model', 'written', 'returned'],
      examples.map(e => {
        // Truncate the RENDERED form, not the raw string: one control character
        // becomes six characters of escape, so slicing first still overflows.
        let shown = JSON.stringify(e.s.got);
        if (shown.length > 34) shown = shown.slice(0, 33) + '\u2026"';
        return [e.name, e.s.model, JSON.stringify(e.s.wrote), shown];
      }));
  }
}

say('---');
say('');
say('Reference models of these techniques, with everything else held equal, are in');
say('`r_and_d/compare.js`. That isolates the design ideas; this measures the software.');

if (JS_PATH) {
  DATA.generated = new Date().toISOString().slice(0, 10);
  DATA.spabVersion = require('../src/js/spab.js').VERSION;
  DATA.libraries = ADAPTERS.map(a => ({
    name: a.name, source: a.source, technique: a.technique, url: a.url,
    vendor: a.vendor || null, family: a.family || null,
    lengthPreserving: !!a.lengthPreserving, integrity: !!a.integrity,
    bestFor: a.bestFor || null,
    ran: live.indexOf(a) >= 0, install: a.install, limits: a.limits || null
  }));
  DATA.known = require('./known-implementations.js');
  var lens = [];
  samples.forEach(function (x) { SCALES.forEach(function (k) { lens.push(x.text.length * k); }); });
  DATA.scope = { samples: samples.length, payloads: payloads.length, scales: SCALES,
    models: Object.keys(MODELS).length,
    docChars: [Math.min.apply(null, lens), Math.max.apply(null, lens)],
    secretBytes: [Math.min.apply(null, payloads.map(function (x) { return x.bytes; })),
                  Math.max.apply(null, payloads.map(function (x) { return x.bytes; }))],
    payloadList: payloads.map(function (x) { return x.bytes; }) };
  DATA.catalog = Object.keys(MODELS).map(describe);
  fs.mkdirSync(path.dirname(JS_PATH), { recursive: true });
  fs.writeFileSync(JS_PATH,
    '/* Generated by comparisons/run.js --js. Do not edit by hand. */\n' +
    'window.SPAB_ROBUSTNESS = ' + JSON.stringify(DATA, null, 2) + ';\n');
  console.error('wrote ' + JS_PATH);
}

if (MD_PATH) {
  fs.mkdirSync(path.dirname(MD_PATH), { recursive: true });
  fs.writeFileSync(MD_PATH, out.join('\n') + '\n');
  console.error('\nwrote ' + MD_PATH);
}
